Repository Team-PATCH/Harmony-iOS, pull requests merged in 2024-07, with the labels that each got.

#10 프로젝트 파일 설정
  Harmony/Harmony.xcodeproj/project.pbxproj
Labels: ⚙️Setting

#11 프로젝트 트리 구조 설정
  Harmony/Harmony.xcodeproj/project.pbxproj
  Harmony/Harmony/Utilities/Extensions/Color+Extensions.swift
Labels: ⚙️Setting

#17 PR 템플릿 버그 수정
  .github/ISSUE_TEMPLATE/bug_issue_template.md
  .github/ISSUE_TEMPLATE/issue_template.md
  .github/PR_TEMPLATE/pull_request_template.md
Labels: 🐛 Bug

#15 추억카드 조회 로직 및 관련 뷰 전체 틀 작업
  Harmony/Harmony.xcodeproj/project.pbxproj
  Harmony/Harmony.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Harmony/Harmony/Models/MemoryCardModel.swift
  Harmony/Harmony/Resources/font/Pretendard-Black.ttf
  Harmony/Harmony/Resources/font/Pretendard-Bold.ttf
  Harmony/Harmony/Resources/font/Pretendard-ExtraBold.ttf
  Harmony/Harmony/Resources/font/Pretendard-ExtraLight.ttf
  Harmony/Harmony/Resources/font/Pretendard-Light.ttf
  Harmony/Harmony/Resources/font/Pretendard-Medium.ttf
  Harmony/Harmony/Resources/font/Pretendard-Regular.ttf
  Harmony/Harmony/Resources/font/Pretendard-SemiBold.ttf
  Harmony/Harmony/Resources/font/Pretendard-Thin.ttf
  Harmony/Harmony/Services/MemoryCardService.swift
  Harmony/Harmony/Utilities/Extensions/Color+Extensions.swift
  Harmony/Harmony/Utilities/Extensions/Font+Extensions.swift
  Harmony/Harmony/Utilities/Extensions/UIApplication+Extensions.swift
  Harmony/Harmony/Utilities/Extensions/View+Extensions.swift
  Harmony/Harmony/Utilities/FormatDate.swift
  Harmony/Harmony/ViewModels/MemoryCardViewModel.swift
  Harmony/Harmony/Views/Home/MemoryCard/MemoryCardDetailView.swift
  Harmony/Harmony/Views/Home/MemoryCard/MemoryCardView.swift
  Harmony/Harmony/Views/Home/MemoryCard/MemoryCardsView.swift
  Harmony/Harmony/Views/Home/MemoryCard/MemoryChatView.swift
  Harmony/Harmony/Views/Home/SearchBarView.swift
Labels: ✨Feature

#36 Certificate & Provisioning Profile 생성 및 등록
  .gitignore
  Harmony/Harmony.xcodeproj/project.pbxproj
Labels: ⚙️Setting

#39 Package resolved 관련 버그 해결 및 gitignore 추가 수정
  .gitignore
  Harmony/Harmony.xcodeproj/project.pbxproj
Labels: ⚙️Setting

#73 추억 카드 생성 뷰 구현 작업
  Harmony/Harmony.xcodeproj/project.pbxproj
  Harmony/Harmony/Utilities/ImagePicker.swift
  Harmony/Harmony/Views/Home/HomeView.swift
  Harmony/Harmony/Views/MemoryCard/MemoryCardCreateView.swift
  Harmony/Harmony/Views/MemoryCard/YearPickerView.swift
Labels: ✨Feature
